export const REGISTER_START= 'REGISTER_START'
export const REGISTER_SUCCESS= 'REGISTER_SUCCESS'
export const REGISTER_FAILURE= 'REGISTER_FAILURE'


export const LOGIN_START= 'LOGIN_START'
export const LOGIN_SUCCESS= 'LOGIN_SUCCESS'
export const LOGIN_FAILURE= 'LOGIN_FAILURE'


export const LOGOUT_START= 'LOGOUT_START'
export const LOGOUT_SUCCESS= 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE= 'LOGOUT_FAILURE'

export const GOOGLE_START= 'GOOGLE_START'
export const GOOGLE_SUCCESS= 'GOOGLE_SUCCESS'
export const GOOGLE_FAILURE= 'GOOGLE_FAILURE'


export const FETCH_POPULAR_BOOKS_REQUEST = 'FETCH_POPULAR_BOOKS_REQUEST';
export const FETCH_POPULAR_BOOKS_SUCCESS = 'FETCH_POPULAR_BOOKS_SUCCESS';
export const FETCH_POPULAR_BOOKS_FAILURE = 'FETCH_POPULAR_BOOKS_FAILURE';

export const SET_SELECTED_GENRES = 'SET_SELECTED_GENRES';
export const SET_BOOKS = 'SET_BOOKS';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const REMOVE_ALL_FROM_CART = 'REMOVE_ALL_FROM_CART';

export const SAVE_SHIPPING_DATA = 'SAVE_SHIPPING_DATA';

export const CLEAR_CART= 'CLEAR_CART'

export const ADD_NEW_ORDER='ADD_NEW_ORDER'

export const SET_USER= 'SET_USER'